/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.itteco.samegame;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int background=0x7f020000;
        public static final int balls=0x7f020001;
        public static final int bottom_background=0x7f020002;
        public static final int explosion=0x7f020003;
        public static final int help=0x7f020004;
        public static final int icon=0x7f020005;
        public static final int new_game=0x7f020006;
        public static final int redo=0x7f020007;
        public static final int score=0x7f020008;
        public static final int score_tab2=0x7f020009;
        public static final int score_tab3=0x7f02000a;
        public static final int score_tab4=0x7f02000b;
        public static final int settings=0x7f02000c;
        public static final int top_background=0x7f02000d;
        public static final int undo=0x7f02000e;
    }
    public static final class id {
        public static final int TableLayout01=0x7f05000c;
        public static final int button_go=0x7f050002;
        public static final int cancel=0x7f05000f;
        public static final int done=0x7f050019;
        public static final int enter_uri=0x7f050003;
        public static final int gameView=0x7f050008;
        public static final int id_nr=0x7f050016;
        public static final int listview1=0x7f050011;
        public static final int listview2=0x7f050013;
        public static final int listview3=0x7f050015;
        public static final int ll1=0x7f050010;
        public static final int ll2=0x7f050012;
        public static final int ll3=0x7f050014;
        public static final int name=0x7f05000e;
        public static final int newButton=0x7f050009;
        public static final int newGame=0x7f050000;
        public static final int ok=0x7f050005;
        public static final int overallScore=0x7f050006;
        public static final int quit=0x7f050001;
        public static final int redoButton=0x7f05000b;
        public static final int score=0x7f05000d;
        public static final int selectionScore=0x7f050007;
        public static final int undoButton=0x7f05000a;
        public static final int upload=0x7f050018;
        public static final int user_name=0x7f050017;
        public static final int wv1=0x7f050004;
    }
    public static final class layout {
        public static final int game_over_dialog=0x7f030000;
        public static final int geocade_upload=0x7f030001;
        public static final int help_dialog=0x7f030002;
        public static final int main=0x7f030003;
        public static final int new_score_dialog=0x7f030004;
        public static final int score=0x7f030005;
        public static final int score_list_item=0x7f030006;
        public static final int upload_geocade_dialog=0x7f030007;
        public static final int welcome_dialog=0x7f030008;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int cancel=0x7f04000d;
        public static final int clear_score_log=0x7f04001a;
        public static final int description=0x7f04000e;
        public static final int game_over=0x7f040004;
        public static final int help=0x7f04000a;
        public static final int new_game=0x7f040005;
        public static final int new_score_add_your_name=0x7f040016;
        public static final int ok=0x7f04000c;
        public static final int overall_score=0x7f040001;
        public static final int quit=0x7f04000b;
        public static final int redo=0x7f040008;
        public static final int return_to_game=0x7f040018;
        public static final int return_to_game_score=0x7f040019;
        public static final int score=0x7f040007;
        public static final int selection_score=0x7f040003;
        public static final int selection_score_no_points=0x7f040002;
        public static final int settings=0x7f040006;
        public static final int settings_difficulty=0x7f04000f;
        public static final int settings_difficulty1=0x7f040011;
        public static final int settings_difficulty2=0x7f040012;
        public static final int settings_difficulty3=0x7f040013;
        public static final int settings_difficulty_summary=0x7f040010;
        public static final int settings_fast_animation=0x7f040014;
        public static final int settings_fast_animation_summary=0x7f040015;
        public static final int show_off_globally=0x7f040017;
        public static final int undo=0x7f040009;
    }
}
